[package]
name = "hello_circuit"
type = "bin"
authors = [""]

[dependencies]
binary_merkle_root = { git = "https://github.com/zk-kit/zk-kit.noir", tag = "binary-merkle-root-v0.0.1", directory = "packages/binary-merkle-root" }
ec = { git = "https://github.com/noir-lang/noir-edwards", tag = "v0.1.1" }
